# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20170115_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
