# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20170115_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contri_col',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
