# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20170115_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
