# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_auto_20170115_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='donation.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='donation.UserProfile')),
            ],
        ),
    ]
