# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_auto_20170115_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='deposit',
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_id',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='deposit',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='donation.Group'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='donation.UserProfile'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
