# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_auto_20170115_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_deposit_per_person',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
