# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0015_auto_20170116_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='check_group',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
